---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &OrgScrayMSP
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: OrgScrayMSPMSP

        # ID to load the MSP definition as
        ID: OrgScrayMSPMSP

        MSPDir: organizations/peerOrganizations/org1.fabric.hyperledger.projects.scray.org/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrgScrayMSPMSP.admin', 'OrgScrayMSPMSP.peer', 'OrgScrayMSPMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('OrgScrayMSPMSP.admin', 'OrgScrayMSPMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('OrgScrayMSPMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('OrgScrayMSPMSP.peer')"

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: org1.fabric.hyperledger.projects.scray.org 
              Port: 30001
