apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-tensorflow-job
  labels:
    app: jupyter-tensorflow-job
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-tensorflow-job
  template:
    metadata:
      labels:
        app: jupyter-tensorflow-job
    spec:
      containers:
        - name: scray-ai-container
          image: scray-jupyter_tensorflow-gpu:0.1.1
          workingDir: /opt/scray-sync/
          env:
            - name: JOB_NAME
              value: "timestamp-example"
          volumeMounts:
            - name: ssh-key-volume
              mountPath: "/etc/ssh-key"
            - name: hf-cache
              mountPath: /root/.cache/huggingface/
      volumes:
        - name: ssh-key-volume
          secret:
            secretName: data-ssh-key
            defaultMode: 256
        - name: hf-cache
          persistentVolumeClaim:
            claimName: 'hf-cache'     

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notebooks-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hf-cache
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi