server.port=8082
logging.level.root=INFO
logging.level.io.swagger=INFO
logging.level.org.scray.sync.rest="DEBUG"

springdoc.swagger-ui.path=/swagger-ui.html

springdoc.swagger-ui.use-root-path=true

server.forward-headers-strategy=native
#server.forward-headers-strategy=framework
server.tomcat.remoteip.protocol-header=x-your-protocol-header

spring.security.ignored=/**
auth.enabled=false

#spring.application.name=simple-authz-resource
#app.issuer=http://localhost:8082

# --- Expose /health so your permitAll() actually hits something ---
#management.endpoints.web.exposure.include=health,info
#management.endpoints.web.base-path=/
#management.endpoint.health.probes.enabled=true


security.apiToken=Vmykb4VsXtrakXfAiMuuvsIwwdurKlPOAIFcDTISZLIF2aAN5YKbtx2z3MsAkUPm
authz.server.enabled=false
resource.server.enabled=true



