---
language: java

dist: trusty

jdk:
    - openjdk8

cache:
    directories:
        - $HOME/.m2

jobs:
    include:
        - stage: build-with-tests
          install:
              mvn --settings .maven.xml install -B
        - stage: build-profil-scala-2.11
          install:
              mvn clean install -B -Pscala-2.11
        - stage: deploy-develop
          install:
              mvn clean deploy --settings .maven.xml -B

stages:
    - build-with-tests
    - build-profil-scala-2.12
    - build-profil-scala-2.11
    - name: deploy-develop-scala_2.12
      if: branch = develop AND type != pull_request AND sender IN (obermeier)
    - name: deploy-develop
      if: branch = develop AND type != pull_request AND sender IN (obermeier)

deploy:
    provider: script
    script: scray-examples/ingestion/prometheus_crawler/docker_deploy.sh
    skip_cleanup: true
    on:
       branch: release/docker_hub
