FROM huggingface-transformers-pytorch-deepspeed-latest-gpu:0.1.2

RUN pip install pandas
RUN pip install transformers
RUN pip install accelerate
RUN pip install bitsandbytes
RUN pip install confluent_kafka
RUN pip install kafka-python
RUN pip install datasets