FROM scray-jupyter_tensorflow-gpu:0.1.1

RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
RUN pip install pandas
RUN pip install transformers
RUN pip install accelerate
RUN pip install bitsandbytes
RUN pip install confluent_kafka
RUN pip install kafka-python
