apiVersion: v1
kind: PersistentVolume
metadata:
  name: hf-cache2-vol
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/volume-data/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hf-cache2
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
