apiVersion: v1
kind: Service
metadata:
  name: peer-id 
  labels:
    run: peer-id 
spec:
  type: NodePort
  selector:
    app: peer-id 
  ports:
    - name: peer-gossip
      port: 7051
      protocol: TCP
    - name: peer-chaincode
      port: 30002
      protocol: TCP
    - name: peer-listen
      port: 7051
      protocol: TCP
