---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hl-fabric-data-share-deployment
  labels:
    app: hl-fabric-data-share-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hl-fabric-data-share
  template:
    metadata:
      labels:
        app: hl-fabric-data-share
    spec:
      containers:
        - name: webdav
          image: bytemark/webdav:2.4
          env:
          - name: AUTH_TYPE
            value: "Basic"
          - name: USERNAME
            value: "scray"
          - name: PASSWORD
            value: "scray"
          volumeMounts:
          - name: webdav-data
            mountPath: /var/lib/dav
      volumes:
      - name: webdav-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: hl-fabric-data-share-service
  labels:
    run: hl-fabric-data-share-service
spec:
  type: NodePort
  selector:
    app: hl-fabric-data-share
  ports:
  - name: webdav-port
    port: 80
    nodePort: 30080 
    protocol: TCP
