/*
* generated by Xtext
*/
package scray.hesse;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class HesseDSLStandaloneSetup extends HesseDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new HesseDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

