/*
 * generated by Xtext
 */
package scray.hesse;

import scray.hesse.converters.HesseTerminalConverters;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class HesseDSLRuntimeModule extends scray.hesse.AbstractHesseDSLRuntimeModule {

	@Override
	public Class<? extends org.eclipse.xtext.conversion.IValueConverterService> bindIValueConverterService() {
		return HesseTerminalConverters.class;
	}
}
