---
apiVersion: v1
kind: Pod
metadata:
  name: nrw-traffic-client
  labels:
    app: nrw-traffic-client
spec:
  containers:
    - name: nrw-traffic-client
      image: scrayorg/nrw-traffic-client
      imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nrw-traffic-client 
  labels:
    run: nrw-traffic-client
spec:
  type: NodePort
  selector:
    app: nrw-traffic-client
  ports:
  - name: nrw-traffic-client-metrics
    port: 8080
    nodePort: 30082 
    protocol: TCP
      