apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-tensorflow-job
  labels:
    app: jupyter-tensorflow-job
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-tensorflow-job
  template:
    metadata:
      labels:
        app: jupyter-tensorflow-job
    spec:
      containers:
        - name: scray-jupyter-tensorflow-latest-gpu
          image: scray-jupyter_tensorflow-gpu:0.1.1
          workingDir: /opt/scray-sync/
          env:
            - name: JOB_NAME
              value: "timestamp-example"
          volumeMounts:
            - name: notebooks
              mountPath: /mnt/ext-notebooks/
            - name: ssh-key-volume
              mountPath: "/etc/ssh-key"
      volumes:
        - name: notebooks
          persistentVolumeClaim:
            claimName: notebooks-pv-claim
              - name: my-secret
        - name: ssh-key-volume
          secret:
            secretName: data-ssh-key
            defaultMode: 256

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notebooks-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi