apiVersion: v1
kind: PersistentVolume
metadata:
  name: scray-notebooks-vol3
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/c/tmp/vol1"
