apiVersion: v1
kind: PersistentVolume
metadata:
  name: scray-notebooks-vol2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "C/tmp"
