apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"jupyter-tensorflow-job"},"name":"jupyter-tensorflow-job","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"jupyter-tensorflow-job"}},"template":{"metadata":{"labels":{"app":"jupyter-tensorflow-job"}},"spec":{"containers":[{"env":[{"name":"JOB_NAME","value":"timestamp-example"}],"image":"scrayorg/scray-jupyter_tensorflow-gpu:0.1.1","name":"scray-jupyter-tensorflow-latest-gpu","volumeMounts":[{"mountPath":"/mnt/ext-notebooks/","name":"notebooks"},{"mountPath":"/etc/ssh-key","name":"ssh-key-volume"}],"workingDir":"/opt/scray-sync/"}],"volumes":[{"name":"notebooks","persistentVolumeClaim":{"claimName":"notebooks-pv-claim"}},{"name":"ssh-key-volume","secret":{"defaultMode":256,"secretName":"data-ssh-key"}}]}}}}
    creationTimestamp: "2023-06-17T15:36:01Z"
    generation: 1
    labels:
      app: jupyter-tensorflow-job
    name: jupyter-tensorflow-job
    namespace: default
    resourceVersion: "10459487"
    uid: 29ea23cc-de04-4a37-a3c9-6e2650ddae84
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: jupyter-tensorflow-job
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: jupyter-tensorflow-job
      spec:
        containers:
        - env:
          - name: JOB_NAME
            value: timestamp-example
          image: scrayorg/scray-jupyter_tensorflow-gpu:0.1.1
          imagePullPolicy: IfNotPresent
          name: scray-jupyter-tensorflow-latest-gpu
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /mnt/ext-notebooks/
            name: notebooks
          - mountPath: /etc/ssh-key
            name: ssh-key-volume
          workingDir: /opt/scray-sync/
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: notebooks
          persistentVolumeClaim:
            claimName: notebooks-pv-claim
        - name: ssh-key-volume
          secret:
            defaultMode: 256
            secretName: data-ssh-key
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2023-06-17T15:36:01Z"
      lastUpdateTime: "2023-06-17T15:40:36Z"
      message: ReplicaSet "jupyter-tensorflow-job-65f77c54c8" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2023-06-22T08:26:50Z"
      lastUpdateTime: "2023-06-22T08:26:50Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
