---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter
  labels:
    app: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      containers:
        - name: jupyter-container
          image:  jupyter/all-spark-notebook
          volumeMounts:
          - name: config
            mountPath: /home/jovyan/work
            subPath: scray/scray-examples/persistent-traffic-data/analytics-workbench/notebooks
          - name: config
            mountPath: /home/jovyan/.jupyter/jupyter_notebook_config.py
            subPath: scray/scray-examples/persistent-traffic-data/analytics-workbench/conf/jupyter_notebook_config.py
          - name: config
            mountPath: /mnt/
      initContainers:
      - name: github-config-loader
        image: alpine/git
        command: ['/bin/sh', '-c']
        args: ['cd /mnt/config && git clone --single-branch -b feature/ingestion-examples https://github.com/scray/scray.git && chmod -R a+rw ./scray']
        volumeMounts:
        - name: config
          mountPath: /mnt/config
      volumes:
      - name: config
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter
  labels:
    run: jupyter
spec:
  type: NodePort
  selector:
    app: jupyter
  ports:
  - name: jupyter-port
    port: 8888
    nodePort: 30084 
    protocol: TCP