apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose -f docker-compose-test-net.yaml -f docker-compose-couch.yaml
      -f docker-compose-ca.yaml convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: ca-org2
  name: ca-org2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ca-org2
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose -f docker-compose-test-net.yaml -f docker-compose-couch.yaml
          -f docker-compose-ca.yaml convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/invoicehyperlederfabric_test: "true"
        io.kompose.service: ca-org2
    spec:
      containers:
      - args:
        - sh
        - -c
        - fabric-ca-server start -b admin:adminpw -d
        env:
        - name: FABRIC_CA_HOME
          value: /etc/hyperledger/fabric-ca-server
        - name: FABRIC_CA_SERVER_CA_NAME
          value: ca-org2
        - name: FABRIC_CA_SERVER_PORT
          value: "8054"
        - name: FABRIC_CA_SERVER_TLS_ENABLED
          value: "true"
        image: hyperledger/fabric-ca:latest
        imagePullPolicy: ""
        name: ca-org2
        ports:
        - containerPort: 8054
        resources: {}
        volumeMounts:
        - mountPath: /etc/hyperledger/fabric-ca-server
          name: ca-org2-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: ca-org2-claim0
        persistentVolumeClaim:
          claimName: ca-org2-claim0
status: {}
