apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose -f docker-compose-test-net.yaml -f docker-compose-couch.yaml
      -f docker-compose-ca.yaml convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: ca-orderer
  name: ca-orderer
spec:
  ports:
  - name: "9054"
    port: 9054
    targetPort: 9054
  selector:
    io.kompose.service: ca-orderer
status:
  loadBalancer: {}
