apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose -f docker-compose-test-net.yaml -f docker-compose-couch.yaml
      -f docker-compose-ca.yaml convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: peer0-org2-example-com
  name: peer0-org2-example-com
spec:
  ports:
  - name: "9051"
    port: 9051
    targetPort: 9051
  selector:
    io.kompose.service: peer0-org2-example-com
status:
  loadBalancer: {}
